CREATE TABLE contacts (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);


INSERT INTO contacts (ID, FIRST_NAME, LAST_NAME) VALUES (
    1, 'Kyryl', 'Starikov'
);